plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.8'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'jacoco'
}

group = 'com.eskcti.algashop'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-flyway'
	implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-authorization-server'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.session:spring-session-jdbc'
	implementation 'org.flywaydb:flyway-database-postgresql'
	implementation 'org.apache.commons:commons-lang3:3.20.0'
	implementation 'com.fasterxml.uuid:java-uuid-generator:5.2.0'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'
	testCompileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-authorization-server-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-flyway-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.assertj:assertj-core:3.27.3'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

def jacocoCoverageExcludes = [
	'**/AuthorizationServerApplication.class',
	'**/AuthorizationServerApplicationTests.class',
	'**/DomainException.class',
	'**/SpringDataAuditingConfig.class',
	'**/ApiExceptionHandler.class',
	'**/AuthorizationServerSecurityConfig.class',
	'**/HttpSessionConfig.class',
	'**/PasswordEncoderConfig.class',
	'**/OAuth2PersistenceConfig.class',
	'**/OAuth2TokenCustomizerConfig.class',
	'**/OidcLogoutSuccessHandlerConfig.class'
]

jacocoTestReport {
	dependsOn test
	executionData test
	reports {
		xml.required = true
		html.required = true
	}
	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, exclude: jacocoCoverageExcludes)
		}))
	}
}

jacocoTestCoverageVerification {
	dependsOn test
	executionData test
	violationRules {
		rule {
			limit {
				minimum = 0.90
			}
		}
	}
	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, exclude: jacocoCoverageExcludes)
		}))
	}
}

check.dependsOn jacocoTestCoverageVerification
